#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

# use container based infrastructure (no sudo possible)
sudo: false

cache:
  directory:
    - $HOME/.composer/cache/files

php: [5.5, 5.6, 7, hhvm]

before_install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - phpunit --configuration ./tests/phpunit.xml.dist
  # tests
  - cd ./tests/example-usage && composer install -vvv --profile
  - ls -ashF bin
  - bin/phantomjs -v

# reduce commit history of git checkout
git:
  depth: 5
